### PR TITLE
Group modules by technology

### PR DESCRIPTION
**Pull request by whoot**
Right now mirage just prints every module in one big blog, which is very cluttered and not even sorted alphabetically.

So I changed the way the modules are printed and grouped them by protocol to give everything a much cleaner look.

Examples:
```
#> ./mirage_launcher --list

┌BT Modules──────┬────────────────────────────────────────────┐
│ Name    │ Type │ Description                                │
├─────────┼──────┼────────────────────────────────────────────┤
│ bt_info │ info │ Information module for Bluetooth interface │
│ bt_scan │ scan │ Scan module for Bluetooth Devices          │
└─────────┴──────┴────────────────────────────────────────────┘ 

┌BTLE Modules──┬────────────┬───────────────────────────────────────────────────────────────────────────┐
│ Name         │ Type       │ Description                                                               │
├──────────────┼────────────┼───────────────────────────────────────────────────────────────────────────┤
│ ble_adv      │ spoofing   │ Spoofing module simulating a Bluetooth Low Energy advertiser              │
│ ble_connect  │ action     │ Connection module for Bluetooth Low Energy devices                        │
│ ble_crack    │ bruteforce │ Enumerates all possible values of PIN in order to find the Temporary Key  │
│ ble_discover │ discover   │ Discovery module for Bluetooth Low Energy ATT / GATT layers               │
│ ble_hijack   │ attack     │ Hijacking module for Bluetooth Low Energy Connections                     │
│ ble_info     │ info       │ Information module for Bluetooth Low Energy interface                     │
│ ble_jam      │ attack     │ Jamming module for Bluetooth Low Energy advertisements and connections    │
│ ble_master   │ spoofing   │ This module permits the User to interact with Bluetooth Low Energy slaves │
│ ble_mitm     │ attack     │ Man-in-the-Middle module for Bluetooth Low Energy devices                 │
│ ble_monitor  │ monitoring │ HCI Monitoring module for Blutooth Low Energy                             │
│ ble_pair     │ action     │ Pairing module for Bluetooth Low Energy devices                           │
│ ble_scan     │ scan       │ Scan module for Bluetooth Low Energy devices                              │
│ ble_slave    │ spoofing   │ Spoofing module simulating a Bluetooth Low Energy slave                   │
│ ble_sniff    │ sniff      │ Sniffing module for Bluetooth Low Energy devices                          │
└──────────────┴────────────┴───────────────────────────────────────────────────────────────────────────┘ 

┌ESB Modules─┬──────────┬────────────────────────────────────────────────────────────────────────────┐
│ Name       │ Type     │ Description                                                                │
├────────────┼──────────┼────────────────────────────────────────────────────────────────────────────┤
│ esb_info   │ info     │ Information module for Enhanced ShockBurst interface                       │
│ esb_inject │ action   │ Injection module for Enhanced ShockBurst communications                    │
│ esb_prx    │ spoofing │ This module permits the User to simulate an Enhanced ShockBurst PRX device │
│ esb_ptx    │ spoofing │ This module permits the User to simulate an Enhanced ShockBurst PTX device │
│ esb_scan   │ scan     │ Scan module for Enhanced ShockBurst Devices                                │
│ esb_sniff  │ sniff    │ Sniffing module for Enhanced ShockBurst communications                     │
└────────────┴──────────┴────────────────────────────────────────────────────────────────────────────┘ 

┌IR Modules─┬────────┬─────────────────────────────────────┐
│ Name      │ Type   │ Description                         │
├───────────┼────────┼─────────────────────────────────────┤
│ ir_info   │ info   │ Information module for IR interface │
│ ir_inject │ action │ Injection module for IR signals     │
│ ir_sniff  │ sniff  │ Sniffing module for IR signals      │
└───────────┴────────┴─────────────────────────────────────┘ 

┌Mosart Modules──────┬────────┬─────────────────────────────────────────────────┐
│ Name               │ Type   │ Description                                     │
├────────────────────┼────────┼─────────────────────────────────────────────────┤
│ mosart_info        │ info   │ Information module for Mosart interface         │
│ mosart_inject      │ action │ Injection module for Mosart devices             │
│ mosart_keyinjector │ attack │ Keystrokes injection module for Mosart keyboard │
│ mosart_keylogger   │ attack │ Keystrokes logger module for Mosart keyboard    │
│ mosart_scan        │ scan   │ Scanning module for Mosart devices              │
│ mosart_sniff       │ sniff  │ Sniffing module for Mosart devices              │
└────────────────────┴────────┴─────────────────────────────────────────────────┘ 

┌WiFi Modules──┬──────────┬────────────────────────────────────────────────┐
│ Name         │ Type     │ Description                                    │
├──────────────┼──────────┼────────────────────────────────────────────────┤
│ wifi_deauth  │ attack   │ Deauthentication module for WiFi networks      │
│ wifi_info    │ info     │ Information module for Wifi interface          │
│ wifi_rogueap │ spoofing │ Spoofing module simulating a fake Access Point │
│ wifi_scan    │ scan     │ Scan module for Wifi Access Point and Stations │
└──────────────┴──────────┴────────────────────────────────────────────────┘ 

┌ZigBee Modules─────┬────────┬─────────────────────────────────────────────┐
│ Name              │ Type   │ Description                                 │
├───────────────────┼────────┼─────────────────────────────────────────────┤
│ zigbee_deauth     │ attack │ Deauthentication module for Zigbee networks │
│ zigbee_floodassoc │ attack │ Flooding module for Zigbee communications   │
│ zigbee_info       │ info   │ Information module for Zigbee interface     │
│ zigbee_inject     │ action │ Injection module for Zigbee communications  │
│ zigbee_scan       │ scan   │ Scan module for Zigbee Devices              │
│ zigbee_sniff      │ sniff  │ Sniffing module for Zigbee communications   │
└───────────────────┴────────┴─────────────────────────────────────────────┘ 

┌Other Modules─────┬──────┬─────────────────────────────────────────────────────────┐
│ Name             │ Type │ Description                                             │
├──────────────────┼──────┼─────────────────────────────────────────────────────────┤
│ mouse_visualizer │ tool │ Visualization module allowing to display mice movements │
└──────────────────┴──────┴─────────────────────────────────────────────────────────┘ 

```

Filtering for protocols will look like this:
```
#> ./mirage_launcher --list=ble
┌BTLE Modules──┬────────────┬───────────────────────────────────────────────────────────────────────────┐
│ Name         │ Type       │ Description                                                               │
├──────────────┼────────────┼───────────────────────────────────────────────────────────────────────────┤
│ ble_adv      │ spoofing   │ Spoofing module simulating a Bluetooth Low Energy advertiser              │
│ ble_connect  │ action     │ Connection module for Bluetooth Low Energy devices                        │
│ ble_crack    │ bruteforce │ Enumerates all possible values of PIN in order to find the Temporary Key  │
│ ble_discover │ discover   │ Discovery module for Bluetooth Low Energy ATT / GATT layers               │
│ ble_hijack   │ attack     │ Hijacking module for Bluetooth Low Energy Connections                     │
│ ble_info     │ info       │ Information module for Bluetooth Low Energy interface                     │
│ ble_jam      │ attack     │ Jamming module for Bluetooth Low Energy advertisements and connections    │
│ ble_master   │ spoofing   │ This module permits the User to interact with Bluetooth Low Energy slaves │
│ ble_mitm     │ attack     │ Man-in-the-Middle module for Bluetooth Low Energy devices                 │
│ ble_monitor  │ monitoring │ HCI Monitoring module for Blutooth Low Energy                             │
│ ble_pair     │ action     │ Pairing module for Bluetooth Low Energy devices                           │
│ ble_scan     │ scan       │ Scan module for Bluetooth Low Energy devices                              │
│ ble_slave    │ spoofing   │ Spoofing module simulating a Bluetooth Low Energy slave                   │
│ ble_sniff    │ sniff      │ Sniffing module for Bluetooth Low Energy devices                          │
└──────────────┴────────────┴───────────────────────────────────────────────────────────────────────────┘ 

```

Filtering for types will look like this:
```
#> ./mirage_launcher --list=scan
┌BT Modules──────┬───────────────────────────────────┐
│ Name    │ Type │ Description                       │
├─────────┼──────┼───────────────────────────────────┤
│ bt_scan │ scan │ Scan module for Bluetooth Devices │
└─────────┴──────┴───────────────────────────────────┘ 

┌BTLE Modules─────┬──────────────────────────────────────────────┐
│ Name     │ Type │ Description                                  │
├──────────┼──────┼──────────────────────────────────────────────┤
│ ble_scan │ scan │ Scan module for Bluetooth Low Energy devices │
└──────────┴──────┴──────────────────────────────────────────────┘ 

┌ESB Modules──────┬─────────────────────────────────────────────┐
│ Name     │ Type │ Description                                 │
├──────────┼──────┼─────────────────────────────────────────────┤
│ esb_scan │ scan │ Scan module for Enhanced ShockBurst Devices │
└──────────┴──────┴─────────────────────────────────────────────┘ 

┌Mosart Modules──────┬────────────────────────────────────┐
│ Name        │ Type │ Description                        │
├─────────────┼──────┼────────────────────────────────────┤
│ mosart_scan │ scan │ Scanning module for Mosart devices │
└─────────────┴──────┴────────────────────────────────────┘ 

┌WiFi Modules──────┬────────────────────────────────────────────────┐
│ Name      │ Type │ Description                                    │
├───────────┼──────┼────────────────────────────────────────────────┤
│ wifi_scan │ scan │ Scan module for Wifi Access Point and Stations │
└───────────┴──────┴────────────────────────────────────────────────┘ 

┌ZigBee Modules──────┬────────────────────────────────┐
│ Name        │ Type │ Description                    │
├─────────────┼──────┼────────────────────────────────┤
│ zigbee_scan │ scan │ Scan module for Zigbee Devices │
└─────────────┴──────┴────────────────────────────────┘ 

```

### CODE REVIEW

**Comment by RCayre** [comment]
Hi, thanks you for this pull request, it's a good idea.
I think it would be better to implement this feature in a more generic way, allowing Mirage to support new protocols without requiring to update a list of conditionnal tests.
It should also be based on the technology field and not the module name.
If you can modify your PR in that way, it would be awesome. Otherwise, I'll do it in the next few days.

**Comment by whoot** [comment]
Oh, I totally missed that technology field. That does make it easier indeed

**Comment by whoot** [comment]
Done

**Comment by RCayre** [comment]
Thank you very much, it's perfect !

**Pull request merged**
